-- MySQL Script generated by MySQL Workbench
-- Tue Aug  4 12:56:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- =====================================================================
-- LittleLemonDB -- primary build script
--
-- This file is the authoritative, self-contained definition of the
-- LittleLemonDB database. Running it on a clean MySQL 8.0+ server
-- reproduces the schema in full: 8 tables, 10 foreign keys,
-- 6 unique indexes, 4 CHECK constraints, 1 view and 2 triggers.
--
-- TO REBUILD THE DATABASE
--   Open in MySQL Workbench -> SQL editor and execute the whole script,
--   or from a terminal:
--       mysql -u root -p < LittleLemonDB.sql
--
-- TO REVERSE ENGINEER THE MODEL IN MySQL WORKBENCH
--   File -> New Model, then
--   File -> Import -> Reverse Engineer MySQL Create Script
--   Select this file, tick "Place imported objects on a diagram", Execute.
--
--   Tested successfully: imports cleanly with the trigger section in place.
--   Should an older Workbench build stop at the DELIMITER blocks, delete
--   from the "SECTION 3 -- TRIGGERS" banner to the end of the file and
--   import again; the triggers are not needed to draw the diagram, and can
--   be run separately in the SQL editor.
--
-- VERIFIED
--   Executed end to end against MySQL 9.6 on an empty server, producing
--   8 tables, 10 foreign keys, 6 unique indexes, 4 CHECK constraints,
--   1 view and 2 triggers.
--
-- SECTIONS
--   1. Schema and tables      (generated by Workbench Forward Engineering)
--   2. CHECK constraints      (hand-written; not supported by the model editor)
--   3. View and triggers      (hand-written; not supported by the model editor)
--
-- NOTE: this script targets a CLEAN server. Sections 1 and 3 are safe to
-- re-run (IF NOT EXISTS / OR REPLACE / DROP IF EXISTS guards), but the
-- ALTER ... ADD CONSTRAINT statements in section 2 will fail with
-- "Duplicate check constraint name" on a second run. Drop the database
-- first if you need to rebuild from scratch.
-- =====================================================================

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
-- 																																																																						

-- -----------------------------------------------------
-- Schema LittleLemonDB
--
-- 																																																																						
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `LittleLemonDB`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `role` ENUM('waiter', 'chef', 'head_waiter', 'manager', 'host', 'driver') NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `hire_date` DATE NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`staff_id`),
  INDEX `idx_staff_role` (`role` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`menu` (
  `menu_item_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(100) NOT NULL,
  `category` VARCHAR(50) NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `is_available` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`menu_item_id`),
  UNIQUE INDEX `uq_menu_item` (`item_name` ASC, `category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`addresses` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `line1` VARCHAR(100) NOT NULL,
  `line2` VARCHAR(100) NULL,
  `city` VARCHAR(60) NOT NULL,
  `region` VARCHAR(60) NULL,
  `postal_code` VARCHAR(12) NOT NULL,
  `country_code` VARCHAR(2) NOT NULL DEFAULT 'ZA',
  `label` ENUM('home', 'work', 'other') NOT NULL DEFAULT 'home',
  `is_default` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `uq_customer_address` (`customer_id` ASC, `line1` ASC, `postal_code` ASC) VISIBLE,
  INDEX `idx_addresses_postal` (`postal_code` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LittleLemonDB`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`bookings` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `staff_id` INT NULL,
  `booking_date` DATETIME NOT NULL,
  `table_number` INT NOT NULL,
  `party_size` INT NOT NULL DEFAULT 1,
  `status` ENUM('reserved', 'seated', 'completed', 'no_show', 'cancelled') NOT NULL DEFAULT 'reserved',
  PRIMARY KEY (`booking_id`),
  UNIQUE INDEX `uq_table_slot` (`table_number` ASC, `booking_date` ASC) VISIBLE,
  INDEX `idx_bookings_date` (`booking_date` ASC) VISIBLE,
  INDEX `fk_bookings_customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_bookings_staff_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LittleLemonDB`.`customers` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bookings_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `LittleLemonDB`.`staff` (`staff_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `booking_id` INT NULL,
  `staff_id` INT NULL,
  `order_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `order_type` ENUM('dine_in', 'takeaway', 'delivery') NOT NULL DEFAULT 'dine_in',
  PRIMARY KEY (`order_id`),
  INDEX `idx_orders_date` (`order_date` ASC) VISIBLE,
  INDEX `fk_orders_customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_orders_booking_idx` (`booking_id` ASC) VISIBLE,
  INDEX `fk_orders_staff_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `LittleLemonDB`.`customers` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_booking`
    FOREIGN KEY (`booking_id`)
    REFERENCES `LittleLemonDB`.`bookings` (`booking_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `LittleLemonDB`.`staff` (`staff_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`order_items` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `menu_item_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `unit_price` DECIMAL(8,2) NOT NULL,
  `line_total` DECIMAL(10,2) GENERATED ALWAYS AS ((quantity * unit_price)),
  PRIMARY KEY (`order_item_id`),
  UNIQUE INDEX `uq_order_item` (`order_id` ASC, `menu_item_id` ASC) VISIBLE,
  INDEX `fk_items_menu_idx` (`menu_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `LittleLemonDB`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_items_menu`
    FOREIGN KEY (`menu_item_id`)
    REFERENCES `LittleLemonDB`.`menu` (`menu_item_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`order_delivery_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`order_delivery_status` (
  `order_delivery_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `address_id` INT NULL,
  `delivery_date` DATETIME NULL,
  `status` ENUM('pending', 'preparing', 'in_transit', 'delivered', 'cancelled') NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`order_delivery_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `idx_ods_status` (`status` ASC) VISIBLE,
  INDEX `fk_ods_address_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_ods_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `LittleLemonDB`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ods_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `LittleLemonDB`.`addresses` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- CHECK constraints
--
-- Appended by hand. The MySQL Workbench model editor has no UI for
-- CHECK constraints, so these cannot be generated from the .mwb model.
-- They are included here so this script remains a complete and
-- reproducible description of the LittleLemonDB database.
-- Enforced by MySQL 8.0.16 and later; parsed but ignored before that.
-- -----------------------------------------------------
ALTER TABLE `LittleLemonDB`.`menu`
  ADD CONSTRAINT chk_menu_price  CHECK (`price` >= 0);
ALTER TABLE `LittleLemonDB`.`bookings`
  ADD CONSTRAINT chk_party_size  CHECK (`party_size` > 0);
ALTER TABLE `LittleLemonDB`.`order_items`
  ADD CONSTRAINT chk_quantity    CHECK (`quantity` > 0);
ALTER TABLE `LittleLemonDB`.`order_items`
  ADD CONSTRAINT chk_unit_price  CHECK (`unit_price` >= 0);


-- -----------------------------------------------------
-- View `LittleLemonDB`.`v_order_totals`
--
-- Order totals are derived, never stored. There is deliberately no
-- total_cost column on orders: a stored total can fall out of step with
-- the line items it summarises, whereas this view cannot.
-- -----------------------------------------------------
CREATE OR REPLACE VIEW `LittleLemonDB`.`v_order_totals` AS
SELECT
    o.order_id,
    o.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    o.order_date,
    o.order_type,
    COUNT(oi.order_item_id)                AS line_count,
    COALESCE(SUM(oi.line_total), 0.00)     AS total_cost
FROM `LittleLemonDB`.`orders` o
JOIN `LittleLemonDB`.`customers` c
    ON c.customer_id = o.customer_id
LEFT JOIN `LittleLemonDB`.`order_items` oi
    ON oi.order_id = o.order_id
GROUP BY o.order_id, o.customer_id, c.first_name, c.last_name,
         o.order_date, o.order_type;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- =====================================================================
-- SECTION 3 -- TRIGGERS
--
-- Rule: an order of type 'delivery' must name a delivery address.
-- This spans two tables, so a CHECK constraint cannot express it in
-- MySQL. Triggers carry it instead.
--
-- If MySQL Workbench's "Reverse Engineer MySQL Create Script" import
-- fails, delete from this banner to the end of the file and re-import.
-- Run this section separately in the SQL editor afterwards.
-- =====================================================================
USE `LittleLemonDB`;

DROP TRIGGER IF EXISTS `trg_ods_delivery_needs_address_ins`;
DROP TRIGGER IF EXISTS `trg_ods_delivery_needs_address_upd`;

DELIMITER $$

CREATE TRIGGER `trg_ods_delivery_needs_address_ins`
BEFORE INSERT ON `order_delivery_status`
FOR EACH ROW
BEGIN
    IF NEW.address_id IS NULL
       AND (SELECT o.order_type FROM `orders` o
            WHERE o.order_id = NEW.order_id) = 'delivery'
    THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'A delivery order requires address_id.';
    END IF;
END$$

CREATE TRIGGER `trg_ods_delivery_needs_address_upd`
BEFORE UPDATE ON `order_delivery_status`
FOR EACH ROW
BEGIN
    IF NEW.address_id IS NULL
       AND (SELECT o.order_type FROM `orders` o
            WHERE o.order_id = NEW.order_id) = 'delivery'
    THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'A delivery order requires address_id.';
    END IF;
END$$

DELIMITER ;
